＃ ---一般选项---＃

＃网站名称
标题：我的网站

＃您网站的简短说明
描述：我超赞的虚拟证明

＃ ---本地开发选项---
＃如果您的网站是本地托管而不是在GitHub上托管，则您需要取消注释以下两个参数以设置url和baseurl
＃ ***如果不确定这是什么意思，请保留此部分不变。仅在知道自己在做什么时才修改url和baseurl！***

＃网址是没有斜线的网站域名网址
＃网址：“ https://example.com”

＃ baseURL时应该是一个空字符串
＃ baseURL时： “”

＃ ---导航栏选项---＃

＃导航栏中的链接列表
导航栏链接：
  关于我：“ aboutme ”
  资源：
    - 美丽的Jekyll：“ http://deanattali.com/beautiful-jekyll/ ”
    - 学习markdown：“ http://www.markdowntutorial.com/ ”
  作者家：“ http://deanattali.com ”

＃显示在导航栏中的图像-图像必须为正方形（宽度=高度）
＃如果您不希望在导航栏中显示图像，请删除此参数
头像：“ /img/avatar-icon.png ”

＃如果您想在左上角使用图片徽标而不是标题文字，
＃然后指定以下参数
＃ title-img：/ path / to / image

＃ ---背景颜色/图像选项---＃

＃个性化您网站上的颜色。颜色值可以是任何有效的CSS颜色

navbar-col：“＃F5F5F5 ”
navbar-text-col：“＃404040 ”
navbar-children-col：“＃F5F5F5 ”
page-col：“ #FFFFFF ”
link-col：“＃008AFF ”
hover-col：“＃0085A1 ”
footer-col：“＃F5F5F5 ”
footer-text-col：“＃777777 ”
footer-link-col：“＃404040 ”

＃另外，可以将导航栏，页脚和页面背景设置为使用背景图像
＃代替颜色

＃ navbar-img：“ / img / bgimage.png”
＃ footer-img：“ / img / bgimage.png”
＃ page-img：“ / img / bgimage.png”

＃ ---页脚选项---＃

＃更改所有这些值或删除不需要的值。
＃重要：您必须保留“名称”参数，其他所有可以删除的参数
作者：
  名称：某人

＃选择活动的社交网络链接。
＃取消注释要在页脚中显示的链接，并将您的信息添加到每个链接。
＃您可以重新排序项目以定义链接顺序。
＃如果您要添加不在此处的新链接，则还需要编辑_data / SocialNetworks.yml文件
社交网络链接：
  rss：是的
  电子邮件：“ someone@example.com ”
  脸书：deanattali
  github的：daattali
  推特：daattali
＃   reddit的：提供yourname
＃   LinkedIn：daattali
＃   姓：yourname
＃   计算器： “3943160 / daattali”
＃   snapchat：deanat78
＃   的Instagram：deanat78
＃   YouTube的：用户/ deanat78
＃   Spotify的：提供yourname
＃   电话：+14159998888
＃   蒸汽：deanat78
＃   抽搐：您的名字
＃   喊叫：提供yourname

＃选择要在帖子中显示的共享链接
主动共享链接：
  推特：是的
  脸书：true
  LinkedIn：真

＃如何在页脚中显示网站链接
＃如果您不想在页脚中链接，请删除此
url-pretty：“ MyWebsite.com ”   ＃例如 “deanattali.com/beautiful-jekyll”

＃ --- Web统计部分---＃

＃填写您的Google Analytics（分析）gtag.js ID以使用gtag跟踪您的网站
＃ GTAG： “”

＃填写您的Google Analytics（分析）ID，以使用GA跟踪您的网站
＃ google_analytics： “”

＃谷歌代码管理工具ID
＃ GTM： “”

＃ Matomo（又名Piwik）网站统计
＃取消注释以下部分以启用Matomo。退出参数控制
＃是否要允许用户选择退出跟踪。

＃ matomo：
＃   SITE_ID： “9”
＃   URI： “demo.wiki.pro”
＃   退出：true

＃ ---评论---＃

＃如果您想支持Disqus评论，请填写您的Disqus短名称（不是用户名）
＃ disqus： “”

＃如果要使用JustComments，请填写API密钥
＃刚发表的评论：“ ABCD-EFGH-IJKL”

＃要使用Facebook评论，请填写Facebook应用ID
＃ fb_comment_id： “”

＃要使用Staticman注释，请填写存储库，分支和端点
静态人：
  库：＃ GitHub上的用户名/库如。“daattali /美丽，化身”
  branch     ：master ＃如果您不使用`master`分支，那么您还需要更新`staticman.yml`中的`branch`参数。
  端点   ：＃您自己的部署的URL，并带有斜杠（将回退到公共GitLab实例），例如。https：//开头<你的API> / V3 /项/ github上/
  reCaptcha：
    ＃针对Staticman的reCaptcha（可选，但建议用于垃圾邮件防护）
    ＃如果使用reCaptcha，则还必须在staticman.yml中设置这些参数
    siteKey  ：＃使用您自己的站点密钥，您需要在Google上申请一个
    秘密   ：＃通过转到https://staticman3.herokuapp.com/v3/encrypt/ <您的站点秘密>来加密您的密码

＃ ---其他---＃

＃ Facebook的应用程序ID
＃ fb_app_id： “”

＃摘录字长
＃将摘录截断为索引页面上指定的单词数
摘录长度：50

＃用于分隔网站标题和HTML文档标题中的描述的字符
＃和RSS feed标题
标题分隔符：“ - ”

＃ Ruby的日期格式
date_format：“％B％-d，％Y ”

＃ ---无需触摸下面的任何内容（但您可以随意触摸）---＃

＃输出选项（有关Jekyll网站的更多信息）
时区：“美国/温哥华”
降价：kramdown
荧光笔：胭脂
固定链接：/：年-：月-：日-：标题/
分页：5

kramdown：
  输入：GFM

＃默认的YAML值（有关Jekyll网站的更多信息）
默认值：
  - 
    范围：
      路径：“ ”
      类型：“帖子”
    值：
      布局：“发布”
      comments：true   ＃在所有博客文章中添加评论
      social-share：true ＃在所有博客文章中添加社交媒体共享按钮
  - 
    范围：
      路径：“ ”  ＃所有文件
    值：
      布局：“页面”
      show-avatar：true

＃使用标签索引页面并使每个帖子上的标签都可点击
链接标签：true

＃从生产站点中排除这些文件
排除：
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - 宝石文件
  - Gemfile.lock的
  - 许可
  - 自述文件
  - Vagrantfile

＃ prose.io配置
散文：
  rooturl：' _posts '
  媒体：“ img ”
  忽略：
    - 404.html
    - 许可
    - feed.xml
    - _config.yml
    - / _布局
    - / _包括
    - / css
    - / img
    - / js
  元数据：
    _帖子：
      - 名称：“布局”
        领域：
          元素：“隐藏”
          值：“发布”
      - 名称：“标题”
        领域：
          元素：“文字”
          标签：“帖子标题”
          占位符：“标题”
          可变的：真
      - 名称：“字幕”
        领域：
          元素：“ textarea ”
          标签：“字幕”
          占位符：“您的帖子的说明。”
          可变的：真
      - 名称：“日期”
        领域：
          元素：“文字”
          标签：“日期”
          帮助：“输入发布日期。”
          占位符：“ yyyy-mm-dd ”
          可变的：真
      - 名称：“图片”
        领域：
          元素：“文字”
          标签：“图片”
          帮助：“将缩略图添加到您的帖子中。”
          占位符：“缩略图”
          可变的：真
      - 名称：“已发布”
        领域：
          元素：“复选框”
          标签：“发布”
          帮助：“选中以发布帖子，取消选中以隐藏。”

插件：
  - 哲基尔PAGINATE
  - 哲基尔网站地图

＃美丽的杰基尔/院长阿塔利
＃ 2fc73a3a967e97599c9​​763d05e564189
