#site sitting
title by blog
SEOTitle:杨奇的博客| BY Blog
email: starkbarry1102@gmail. com
description: "每个胜利背后都有许多尝试”
keyword: "BY, BY Blog,杨奇的博客，acestark, 杨奇，i0S, Apple, iPhone"
url: "https://acestark. github. io" # your host, for absolute URL
baseurl: "””# for example, '/blog' if your blog hosted on 'host/blog'


# SNS settings
 RSS: false
 weibo_username:  帅气的杨奇
 zhihu_username:  AceStark
 github_username: AceStark
